[package]
name = "qiniu-credential"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2021"
rust-version = "1.56.0"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu Credential SDK for Rust"
keywords = ["qiniu", "storage"]

[dependencies]
hmac = { version = "0.11.0", features = ["std"] }
sha-1 = "0.9.6"
once_cell = "1.8.0"
http = "0.2.4"
mime = "0.3.16"
form_urlencoded = "1.0.1"
serde = "1.0.130"
dyn-clonable = "0.9.0"
auto_impl = { package = "bachue-auto_impl", version = "0.5.1" }
futures-lite = { version = "1.12.0", optional = true }

qiniu-utils = { version = "0.0.4", path = "../utils" }

[dev-dependencies]
anyhow = "1.0.44"
serde_json = "1.0.68"

[features]
default = []
async = ["futures-lite"]
docs = []

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "feature=\"docs\""]
