language: rust
rust:
  - 1.38.0
cache: cargo
matrix:
  include:
    - os: linux
      dist: bionic
      before_script:
        - sudo apt install -yq libcurl4
        - cargo install --force cbindgen
      script:
        - make
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make test
            fi
    - os: windows
      before_script:
        - choco install make curl
        - cargo install --force cbindgen
        - export PATH="$(powershell -Command '("Process", "Machine" | % { [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", "" } | Select -Unique | % { cygpath $_ }) -Join ":"')"
      script:
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              cd qiniu-c
              make -f Makefile.forWindows test
            fi
