language: rust
dist: bionic
rust:
  - 1.38.0
cache: cargo
before_script:
  - sudo apt install -yq libcurl4
script:
  - cargo install --force cbindgen
  - make
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]
    then
      make test
    fi
