language: rust
matrix:
  include:
    - os: linux
      dist: bionic
      rust:
        - 1.38.0
      before_script:
        - sudo apt install -yq libcurl4
        - cargo install --force cbindgen
      script:
        - make
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make test
            fi
    - os: osx
      rust:
        - 1.38.0
      before_script:
        - brew install curl
        - cargo install --force cbindgen
      script:
        - make
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make test
            fi
    - os: windows
      rust:
        - 1.38.0-x86_64-pc-windows-msvc
      before_script:
        - choco install make
        - choco install curl --version=7.67.0
        - cargo install --force cbindgen
        - export PATH="$(powershell -Command '("Process", "Machine" | % { [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", "" } | Select -Unique | % { cygpath $_ }) -Join ":"')"
      script:
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              cd qiniu-c
              mv Makefile.forWindows Makefile
              cp /c/ProgramData/chocolatey/lib/curl/tools/curl-7.67.0-win64-mingw/bin/*.dll .
              cp -r /c/ProgramData/chocolatey/lib/curl/tools/curl-7.67.0-win64-mingw/include/curl .
              cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && make build'
              cp ../target/debug/qiniu_ng_c.dll* .
              cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && make test'
            fi
