language: rust
dist: bionic
rust:
  - 1.38.0
cache: cargo
before_script:
  - sudo apt install -yq libcurl4
script:
  - make
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]
    then
      travis_wait 30 make test
    fi
