language: rust
matrix:
  include:
    - os: linux
      dist: bionic
      rust:
        - 1.38.0
      before_script:
        - sudo apt install -yq curl libcurl4 git-core build-essential pkg-config libssl-dev zlib1g-dev gnupg software-properties-common
        - cargo install --force cbindgen
        - |
            curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main'
            sudo apt-get update -yqq
            sudo apt-get install -yqq clang-5.0
            export PATH="$PATH:/usr/lib/llvm-5.0/bin"
        - |
            export PATH="$PATH:$HOME/.rbenv/bin"
            curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
            eval "$(rbenv init -)"
            rbenv install 2.3.3
            rbenv global 2.3.3
            gem install bundler
      script:
        - make
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make test
            fi
    - os: osx
      rust:
        - 1.38.0
      before_script:
        - brew install curl rbenv llvm
        - |
            export PATH="$(brew --prefix llvm)/bin:$PATH"
        - cargo install --force cbindgen
      script:
        - |
            eval "$(rbenv init -)"
            rbenv install 2.3.3
            rbenv global 2.3.3
            gem install bundler
        - make
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make test
            fi
    - os: windows
      rust:
        - 1.38.0-x86_64-pc-windows-msvc
      before_script:
        - choco install make
        - choco install curl --version=7.67.0
        - cargo install --force cbindgen
        - export PATH="$(powershell -Command '("Process", "Machine" | % { [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", "" } | Select -Unique | % { cygpath $_ }) -Join ":"')"
      script:
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              cd qiniu-c
              cp /c/ProgramData/chocolatey/lib/curl/tools/curl-7.67.0-win64-mingw/bin/*.dll .
              cp -r /c/ProgramData/chocolatey/lib/curl/tools/curl-7.67.0-win64-mingw/include/curl .
              cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && make build'
              cp ../target/debug/qiniu_ng_c.dll* .
              cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && make test'
            fi
