language: rust
rust:
  - 1.36.0
cache: cargo
script:
  - cargo build --verbose --all
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]
    then
      cargo test --verbose --all
    fi
  - |
    cd qiniu-c
    make
