[workspace]

members = [
    "qiniu-rust/credential",
    "qiniu-rust/utils",
    "qiniu-rust/etag",
    "qiniu-rust/upload_token",
    "qiniu-rust/http",
]

[profile.release]
lto = "fat"
codegen-units = 1
