[workspace]

members = [
    "qiniu-rust",
    "qiniu-c",
    "qiniu-rust-http",
    "qiniu-rust-with-libcurl",
    "qiniu-rust-test",
    "qiniu-c-translator",
]

[profile.release]
lto = "fat"
codegen-units = 1
