[package]
name = "qiniu-credential"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu Credential SDK for Rust"
keywords = ["qiniu", "storage"]

[dependencies]
hmac = "0.8.1"
sha-1 = "0.9.1"
url = "2.1.0"
once_cell = "1.4.0"

qiniu-utils = { version = "0.0.4", path = "../utils" }
