include_version = true
braces = "SameLine"
line_length = 120
tab_width = 4
language = "C"
documentation = true
include_guard = "__QINIU_NG_H"
cpp_compat = true
sys_includes = ["curl/curl.h"]
style = "both"

header = """
#ifndef qiniu_ng_char_t
#if defined(_WIN32) || defined(WIN32)
#define qiniu_ng_char_t wchar_t
#else
#define qiniu_ng_char_t char
#endif
#endif

#if defined(_WIN32) || defined(WIN32)
#include <winsock2.h>
#else
#include <netinet/in.h>
#endif
"""

[export]
item_types = ["globals", "enums", "structs", "unions", "typedefs", "opaque", "functions", "constants"]
exclude = ["qiniu_ng_char_t"]

[export.rename]
"in_addr" = "struct in_addr"
"in6_addr" = "struct in6_addr"

[const]
allow_static_const = true

[defines]
feature = "use-libcurl"
