[package]
name = "qiniu"
version = "0.1.0"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu Resource Storage SDK for Rust"

[dependencies]
lazy_static = "1.3.0"
rust-crypto = "0.2.36"
base64 = "0.10.1"
num = "0.2.0"
http = "0.1.18"
url = "2.0.0"
bytesize = "1.0.0"

[dev-dependencies]
reqwest = "0.9.19"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
stringreader = "0.1.1"
tempfile = "3.1.0"
