[package]
name = "qiniu-ffi-struct-macros"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu FFI Struct Proc Macros"
keywords = ["qiniu", "storage"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0.38"
proc-macro2 = "1.0.19"
quote = "1.0.7"
