[package]
name = "qiniu-upload-token"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu Upload Policy / Upload Token Generator / Parser for Rust"
keywords = ["qiniu", "storage"]

[dependencies]
serde_json = "1.0"
assert-impl = "0.1.3"
once_cell = "1.4.0"
thiserror = "1.0"

qiniu-credential = { version = "0.0.4", path = "../credential" }
qiniu-utils = { version = "0.0.4", path = "../utils" }
